### ISSUE TITLE
[reddit] posts, comments sorting?

### ISSUE THREAD

**Issue by 097115** [snoofox/snoo#1]
It seems, for reddit, snoo uses the default posts and comments sorting (which are probaby both 'top'?).

Would it be possible to add 'new' for posts (looks [like this](https://www.reddit.com/r/golang/new), latest first) and 'old' for comments (latest last)?

**Comment by snoofox** [comment]
I could implement sorting feature, but reddit have different api for fetching posts of different category such as new, so that would be kinda challenging, i need some time to think how am i gonna approach this problem 👀🙏

**Comment by 097115** [comment]
If (probably not, but just in case), you use RSS for obtaining posts, then almost every reddit's page supports `.rss` or `.json` suffixes, like this:

    https://www.reddit.com/r/golang/new/.rss?limit=200

And thanks for your interest :)

**Comment by snoofox** [comment]
Yeah, that’s exactly what I’m using — Reddit’s `.json` API, since RSS doesn’t include comments.
The tricky part isn’t fetching data, it’s figuring out the UX. Should users be able to subscribe directly to /new or /top, or should there be a shortcut key (s maybe) to switch between categories?

Subscriptions would be simpler to implement but would increase load times and API calls. A key-based switch feels cleaner but adds another layer of complexity. Still thinking through what’s the best balance there.

**Comment by 097115** [comment]
Ah, I see :)

Thanks for the explanation!

**Comment by snoofox** [comment]
I’ve implemented the sorting feature in the feat/sorting branch. Could you take a look and let me know if everything works as you expected before I merge it into main?

**Comment by 097115** [comment]
Thanks!

So, I do `snoo sub add vim:new`, it understand this new syntax, reports back:

    Subscribing to r/vim:new...
    Successfully subscribed to r/vim:new

Then I launch snoo, and, unofrtunately, still see the default (hot) sorting :) 
Have I missed someting? I do compare it with https://www.reddit.com/r/vim/new/ simly openned in in my browser.

(Just in case, I didn't try to subscribe to r/vim with snoo before just to avoid any possible chaching issues.)

**Comment by snoofox** [comment]
Hey, not sure I fully get the issue you're facing. Is it that you're not seeing new posts even after adding sources like vim:new? Try running `snoo clear` to flush the cache before the command — might help.

Also, I added filtering with the `f` key so you can pick which source to view content from. To avoid seeing the same post repeatedly, I built in de-duplication. For example, if `vim:new` and `vim:best ` already include everything from `vim:hot`, you won’t see `vim:hot` as a filter option. The API still fetches it, but it’s hidden from the filter list.

**Comment by 097115** [comment]
> Is it that you're not seeing new posts even after adding sources like vim:new? 

It's that the posts are still not sorted by `new` :). Not the latest post is displayed first but something else (the "hottest"?).

Now, after your reply, I think that you maybe didn't add that at all? Just the ability to add `:new` sources but the internal sorting still use something else? 

Or maybe I'm just missing something very obvious, sorry :)

**Comment by snoofox** [comment]
Yeah, i wasn't working on that, i misunderstood the assignment, sorry. It seems like maybe i have to create my own sorting feature instead of using reddit's, it'd be much better and faster anyways.

**Comment by snoofox** [comment]
I have implemented sorting feature, can u check and see if it works for you?

**Comment by 097115** [comment]
> can u check and see if it works for you?

It does, thanks a lot!

Would be great if it'd be possible to change sorting for the comments, too, but I'd probably be the only user, who would use that, I guess :). 

Thanks again, and feel free to close the issue after merging.

**Comment by snoofox** [comment]
Since you're my only known user, I went ahead and implemented comment sorting as well. Don’t hesitate to raise more issues — thanks again!

**Comment by 097115** [comment]
Sorry for the noise, just wanted to add another thank you :)

(And I've just tested the latest version, everything's OK!)
